# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1325679248);
user_pref("app.update.lastUpdateTime.background-update-timer", 1325679230);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1325679356);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1325584341);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1325679300);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1325678947);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.download.lastDir", "AAAAAAFSAAIAAQxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADKQPf8SCsAAAAFPzMJRG93bmxvYWRzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU/fcpA+h0AAAAAAAAAAP////8AAAkgAAAAAAAAAAAAAAAAAAAAB3NqYWd0YXAAABAACAAAykDp7AAAABEACAAAykDsDQAAAAEACAAFPzMAAL7sAAIAJk1hY2ludG9zaCBIRDpVc2VyczoAc2phZ3RhcDoARG93bmxvYWRzAA4AFAAJAEQAbwB3AG4AbABvAGEAZABzAA8AGgAMAE0AYQBjAGkAbgB0AG8AcwBoACAASABEABIAF1VzZXJzL3NqYWd0YXAvRG93bmxvYWRzAAATAAEvAAAVAAIADv//AAA=");
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 0);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.link.open_external", 2);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 1);
user_pref("browser.offline", false);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.preferences.privacy.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.24");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.checkCompatibility", false);
user_pref("extensions.checkUpdateSecurity", false);
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.24");
user_pref("extensions.lastAppVersion", "3.6.24");
user_pref("extensions.update.autoUpdate", false);
user_pref("extensions.update.autoUpdateEnabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("filepicker.lastTypeIndex", 0);
user_pref("idle.lastDailyNotification", 1322947676);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.http", "localhost");
user_pref("network.proxy.http_port", 9999);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.ssl", "localhost");
user_pref("network.proxy.ssl_port", 9999);
user_pref("network.proxy.type", 1);
user_pref("places.last_vacuum", 1322947676);
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("pref.browser.homepage.disable_button.blank_page", false);
user_pref("pref.privacy.disable_button.clear_history", false);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.item.cookies", true);
user_pref("privacy.item.passwords", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("profile.confirm_automigration", false);
user_pref("security.OCSP.disable_button.managecrl", false);
user_pref("security.disable_button.openCertManager", false);
user_pref("security.disable_button.openDeviceManager", false);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_entering_weak.show_once", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("security.warn_viewing_mixed.show_once", false);
user_pref("signon.autofillForms", false);
user_pref("signon.prefillForms", false);
user_pref("signon.rememberSignons", false);
user_pref("xpinstall.whitelist.required", false);
